title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-05
owner: ucsb-cs156-f24
repo_name: team02-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishanjain-team02-addFixtures","number":69,"title":"added fixtures for UCSBOrganizations","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/69"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-team02-addFixtures","number":68,"title":"Added fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/68"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-fixtures","number":67,"title":"created fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/67"},{"author":{"id":"MDQ6VXNlcjI5MzkxNjA1","is_bot":false,"login":"17acastelein","name":""},"headRefName":"17acastelein-DCMI-fixtures","number":64,"title":"added fixtures file for DCMI","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/64"}]
