title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-05
owner: ucsb-cs156-f24
repo_name: team02-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"articles-placeholder-navbar","number":88,"title":"copied placeholders for articles pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/88"},{"author":{"id":"MDQ6VXNlcjI5MzkxNjA1","is_bot":false,"login":"17acastelein","name":""},"headRefName":"ac-dcmi-table","number":87,"title":"Table component for menu items","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/87"},{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishanjain-placeholder","number":86,"title":"ishanjain organizations placeholder","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/86"},{"author":{"id":"MDQ6VXNlcjcxNzI5MTQy","is_bot":false,"login":"Bruhwilliam","name":"William Lau"},"headRefName":"bruhwilliam-RecommendationRequest-formcomponent","number":85,"title":"Recommendation Request form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/85"}]
