title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-05
owner: ucsb-cs156-f24
repo_name: team02-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishanjain-formComponentPlusTests","number":82,"title":"organizations form plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/82"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-tableComponent","number":81,"title":"created table component for MenuItemReview plus test","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/81"},{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"articles-table-component","number":80,"title":"added table component for articles plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/80"}]
