title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-05
owner: ucsb-cs156-f24
repo_name: team02-f24-05
pull_requests: [{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-team02-tableComp","number":94,"title":"Created the table component for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/94"},{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishanjain-createPage","number":89,"title":"Ishanjain create organization page and tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/89"},{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishanjain-placeholder","number":86,"title":"ishanjain organizations placeholder","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/86"},{"author":{"id":"MDQ6VXNlcjcxNzI5MTQy","is_bot":false,"login":"Bruhwilliam","name":"William Lau"},"headRefName":"bruhwilliam-RecommendationRequest-formcomponent","number":85,"title":"Recommendation Request form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/85"}]
