title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-05
owner: ucsb-cs156-f24
repo_name: team02-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"basperheim1-styling","number":142,"title":"Changed Styling","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/142"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-End2End","number":141,"title":"menuItemReview end2 end","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/141"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-editPage","number":139,"title":"Integration Test for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-05/pull/139"}]
